Part a
sobel121/TypeRacerAlon pull request #1
Opened 2023-07-02 08:26 UTC by sobel121

2023-07-02 12:07 UTC, amityosef requested changes

2023-07-02 12:07 UTC, amityosef commented on index.html
> +  <title>Type Racer</title>
fix

2023-07-02 12:07 UTC, amityosef commented on src/TargetSentence.tsx
> +export default function TargetSentence({done, todo, currentWordDone, currentWordTodo}: {done: string[], todo: string[], currentWordDone: string, currentWordTodo: string}) {
תוציא את הטייפ למשתנה

2023-07-02 12:07 UTC, amityosef commented on src/TargetSentence.tsx
> +    );
תשנה את זה לmui

2023-07-02 12:07 UTC, amityosef commented on src/appContent.css
> +}
גם את זה

2023-07-02 12:07 UTC, amityosef commented on src/appContent.tsx
> +        if (sentenceWords.current[currentTargetWordIndex].includes(event.currentTarget.value)) {
destruct את המשתנים מתוך event.currentTarget.

2023-07-02 12:07 UTC, amityosef commented on src/appContent.tsx
> +        const typeTextArea = document.getElementById("textInputArea")! as HTMLInputElement;
fix !

2023-07-02 12:07 UTC, amityosef commented on src/appContent.tsx
> +        const typeTextArea = document.getElementById("textInputArea")! as HTMLInputElement;
document.getElementById("textInputArea") not in react

2023-07-02 12:07 UTC, amityosef commented on src/appContent.tsx
> +        const typeTextArea = document.getElementById("textInputArea")! as HTMLInputElement;
as HTMLInputElement ---- dont write this

2023-07-02 12:07 UTC, amityosef commented on src/constants.ts
> +    "All humans are mortal beings who eventually experience the end of life.",
fix

2023-07-02 12:07 UTC, amityosef commented on src/constants.ts
> +    "Dogs, members of the Canidae family, belong to the class of mammals with diverse breeds.",
fix

2023-07-02 12:07 UTC, amityosef commented on src/constants.ts
> +    "fãilure fãilure fãilure fãilure fãilure fãilure fãilure fãilure fãilure fãilure fãilure fãilure fãilure fãilure fãilure fãilure fãilure."
בעיברית בבקשה

2023-07-03 07:10 UTC, itayboop requested changes

2023-07-03 07:10 UTC, itayboop commented on src/App.tsx
> +require("./App.css");
require??? are you in js?
`import 'App.css'`

2023-07-03 07:10 UTC, itayboop commented on src/appContent.tsx
> +require('./appContent.css')
again
import

2023-07-03 07:10 UTC, itayboop commented on src/appContent.tsx
> +    const [currentWordTodo, setCurrentWordTodo] = useState(sentenceWords.current[0]);
you dont need this state

2023-07-03 07:10 UTC, itayboop commented on src/utils.ts
> +    || (value ===sentenceWords[currentTargetWordIndex] && sentenceWords.length === currentTargetWordIndex + 1)
split those into several lines so it will be more readable

2023-07-03 07:38 UTC, 10612 requested changes
Put each component in a separate file

2023-07-03 07:38 UTC, 10612 commented on index.html
> +  <title>Type Racer</title>
This should be implemented in a component

2023-07-03 07:38 UTC, 10612 commented on src/App.tsx
> +require("./App.css");
Why not `import "./App.css"`?

2023-07-03 07:38 UTC, 10612 commented on src/RestartGameButton.tsx
Delete empty file

2023-07-03 07:38 UTC, 10612 commented on src/constants.ts
Give a more indicative name

2023-07-03 07:38 UTC, 10612 commented on src/utils.ts
> +export const isWordComplete = (value: string, sentenceWords: string[], currentTargetWordIndex: number) => {
Change value to a more indicative name

2023-07-03 07:38 UTC, 10612 commented on src/TargetSentence.tsx
> +interface TargetSentenceProps {done: string[], todo: string[], currentWordDone: string, currentWordTodo: string};
{
    prop1: type,
    prop2: type,
    ...
}

2023-07-03 07:38 UTC, 10612 commented on src/appContent.tsx
> +                <button onClick={restartGame} id="restartGameButton">restart game</button>
Put "restart game" in a `strings.ts` file

2023-07-03 07:38 UTC, 10612 commented on src/App.tsx
> +            <h1>type racer</h1>
pur "type racer" in a `strings.ts` file

2023-07-03 07:38 UTC, 10612 commented on src/appContent.tsx
> +                <input type="textArea" onChange={handleInput} ref={textArea} id="textInputArea"></input>
Move input to a separate component

2023-07-09 08:22 UTC, odev954 reviewed
* conventions
* hooks

2023-07-09 08:22 UTC, odev954 commented on package.json
> +    "module-name": "^0.0.1-security",
what is this dep?

2023-07-09 08:22 UTC, odev954 commented on src/components/appContent/appContent.tsx
> +                todo={getTodoWords(done.length + 1, sentenceWords.current)}
use useMemo hook

2023-07-09 08:22 UTC, odev954 commented on src/components/appContent/appContent.tsx
> +                )}
>use useMemo hook

as well

2023-07-09 08:22 UTC, odev954 commented on src/components/appContent/appContent.tsx
> +    };
use useCallback hook

2023-07-09 08:22 UTC, odev954 commented on src/components/targetSentence/TargetSentence.tsx
> +            <span className="targetSentencePart" id="doneWords">{done.join(" ") + " "}</span>
put `done.join(" ") + " "` inside useMemo hook

2023-07-09 08:22 UTC, odev954 commented on src/components/targetSentence/TargetSentence.tsx
> +            <span className="targetSentencePart" id="todoWords">{" " + todo.join(" ")}</span>
put `" " + todo.join(" ")` inside useMemo hook

2023-07-09 08:22 UTC, odev954 commented on src/components/typeInput/TypeInput.tsx
> +    setCurrentTargetWordIndex: React.Dispatch<React.SetStateAction<number>>
you are cupling your code to the type of ` React.Dispatch`, just use regular callback syntax.
example:
```suggestion
    setDone: (done: string[]) => void,  
    setCurrentWordDoneCharacters: React.Dispatch<React.SetStateAction<string>>, //do this here too
    setCurrentTargetWordIndex: React.Dispatch<React.SetStateAction<number>> //do this here too
```

2023-07-09 08:22 UTC, odev954 commented on src/components/typeInput/TypeInput.tsx
> +function TypeInput({sentenceWords, currentTargetWordIndex, setDone, setCurrentWordDoneCharacters, setCurrentTargetWordIndex}:TypeInputProps, textArea: React.ForwardedRef<HTMLInputElement>) {
why you are getting textArea in separate of props? this is not conventional

2023-07-09 08:22 UTC, odev954 commented on src/components/typeInput/TypeInput.tsx
> +    };
use useCallback hook

2023-07-11 08:49 UTC, odev954 reviewed
* use callback
* decouple

2023-07-11 08:49 UTC, odev954 commented on src/components/typeInput/TypeInput.tsx
> +    setCurrentTargetWordIndex: React.Dispatch<React.SetStateAction<number>>,
decouple

2023-07-11 08:49 UTC, odev954 commented on src/components/appContent/appContent.tsx
> +    };
use callback

2023-07-11 10:29 UTC, odev954 approved these changes

2023-07-11 10:30 UTC, merged