Convert to react query
sobel121/TypeRacerAlon pull request #6
Opened 2023-07-18 09:19 UTC by sobel121

2023-07-18 10:44 UTC, 10612 requested changes
Use index files for your components.
api should be at the same level as the components folder.

2023-07-18 10:44 UTC, 10612 commented on package.json
> +    "react-query": "^3.39.3"
remove react-query by running `npm uninstall`

2023-07-18 10:44 UTC, 10612 commented on src/components/appContent/appContent.tsx
You dont need to import React

2023-07-18 10:44 UTC, 10612 commented on src/customHooks/useUpdateLeaderBoard/consants.ts
name this file consts instead of constants (team convention)

2023-07-18 10:44 UTC, 10612 commented on src/customHooks/useUpdateLeaderBoard/localStorageHandler.ts
This belongs in an "api" folder

2023-07-18 10:44 UTC, 10612 commented on src/index.tsx
> +root.render(<React.StrictMode><QueryClientProvider client={queryClient}><App /></QueryClientProvider></React.StrictMode>)
To much in one line

2023-07-18 10:44 UTC, 10612 commented on src/customHooks/useLeaderBoard/utils.ts
> +export const errorMessage = (errorMessage: String) => "An error occurred: " + errorMessage;
It would be more apropriate to put "An error occurred: " in strings and to connect them at the error

2023-07-18 10:44 UTC, 10612 commented on src/customHooks/useLeaderBoard/localStorageHandler.ts
This belongs in an "api" folder

2023-07-18 10:44 UTC, 10612 commented on src/components/appContent/utils.ts
> +) => sentenceWords.slice(doneWordsAmount);
This isn't worth the trouble of using it

2023-07-18 10:44 UTC, 10612 commented on src/components/appContent/utils.ts
> +export const createLeaderBoardObject = (sentenceWords: string[], totalSeconds: number, currentGameId: number) => {
You don't need to get sentenceWords just its length

2023-07-18 10:44 UTC, 10612 commented on src/customHooks/useLeaderBoard/useLeaderBoard.ts
> +    }
Use onError for this

2023-07-18 10:44 UTC, 10612 commented on src/customHooks/useLeaderBoard/useLeaderBoard.ts
> +    }
Why does this exist?

2023-07-18 10:44 UTC, 10612 commented on src/customHooks/useLeaderBoard/useLeaderBoard.ts
> +    const { isLoading, isError, error, data } = useQuery(['leaderBoard'], () => getLeaderBoardFromLocalStorage());
Use unique ids.
You don't need to wrap getLeaderBoardFromLocalStorage with an arrow function.

2023-07-18 10:44 UTC, 10612 commented on src/customHooks/useUpdateLeaderBoard/localStorageHandler.ts
> +export const setLeaderBoardInLocalStorage = (leaderBoard: Contender[]) => localStorage.setItem("leaderBoard" ,JSON.stringify(leaderBoard));
Use a word other than set

2023-07-18 12:48 UTC, 10612 requested changes

2023-07-18 12:48 UTC, 10612 commented on src/api/localStorageApi.ts
Separate files

2023-07-18 12:48 UTC, 10612 commented on src/customHooks/useLeaderBoard/useLeaderBoard.ts
> +        onError: (err) => errorMessage + err,
You need to throw an error for this to work

2023-07-18 12:48 UTC, 10612 commented on src/customHooks/useLeaderBoard/useLeaderBoard.ts
> +        onError: (err) => errorMessage + err,
you can test that this works properly by throwinng an error at getLeaderBoardFromLocalStorage

2023-07-18 13:51 UTC, 10612 commented on src/components/appContent/utils.ts
> +) => sentenceWords.slice(doneWordsAmount);
.

2023-07-18 14:33 UTC, 10612 approved these changes

2023-07-19 06:21 UTC, odev954 reviewed
* use memo
* redundent code
* query key
* conventions

2023-07-19 06:21 UTC, odev954 commented on src/components/appContent/appContent.tsx
> +
use memo on contender

2023-07-19 06:21 UTC, odev954 commented on src/components/appContent/appContent.tsx
> +            updateLeaderBoard(createLeaderBoardContender(sentenceWords.current.length, totalSeconds, currentGameId));
>use memo on contender

redundent, uses the same value as here

2023-07-19 06:21 UTC, odev954 commented on src/customHooks/useLeaderBoard/useLeaderBoard.ts
> +    const { data } = useQuery([gameId.toString], getLeaderBoardFromLocalStorage, {
maybe memory addresses are very random, but man!
```suggestion
    const { data } = useQuery([gameId.toString()], getLeaderBoardFromLocalStorage, {

```

2023-07-19 06:21 UTC, odev954 commented on src/customHooks/useLeaderBoard/useLeaderBoard.ts
> +        },
this will cause the entire page to crush. use the `isError` flag and if it's true, display an error message to the user :)

2023-07-19 06:21 UTC, odev954 commented on src/customHooks/useUpdateLeaderBoard/useUpdateLeaderBoader.ts
> +        mutationKey: ["updateLeaderBoard", String(newContender.id)],
```suggestion
        mutationKey: ["updateLeaderBoard", newContender.id.toString()],

```

2023-07-24 07:35 UTC, merged